.TH SXCS 1 "Jul 2023" "sxcs v0.7.3"
.SH NAME
sxcs - Minimal X11 color picker and magnifier
.SH SYNOPSIS
sxcs [\fBoptions\fR]
.SH DESCRIPTION
.B sxcs
is a minimal X11 color picker and magnifier.
Mouse
.B Button1
will select and print the color to stdout.
The output is TAB separated hex, rgb and hsl.
.B "Scroll Up/Down"
will zoom in and out.
Any other mouse button will quit sxcs.
.P
The keyboard can also be used when
.B \-\-keyboard
is enabled.
The arrow keys
.BR Left ", " Right ", " Up ", " Down
as well as vi\-like
.BR h ", " j ", " k ", " l
are supported for moving the cursor.
By default they move by 16 pixels, if
.B Shift
is used then they move by 1 pixel instead.
.B Space
makes a selection.
.BR q " and " Escape
quits.
.BR + " and " \-
zooms in and out.
.SH OPTIONS
.TP
.BR "--color-none"
disable color output.
.TP
.BR "--hex"
output hex colors.
.TP
.BR "--rgb"
output rgb colors.
.TP
.BR "--hsl"
output hsl colors.
.TP
.BR "--mag-none"
disable magnifier.
.TP
.BI "--mag-filters " "filters"
comma separated list of filter to apply in order.
See the FILTERS section.
.TP
.BR "-o, --one-shot"
quit after a single selection.
.TP
.BR "-q, --quit-on-keypress"
quit on keypress.
.TP
.BR "--keyboard"
enable keyboard control.
.TP
.BR "-h, --help"
Show usage and exit.
.TP
.BR "--version"
Show version and exit.
.SH FILTERS
List of available filters:
.TP
.B "square"
draws a square border.
.TP
.B "xhair"
draws a square crosshair.
.TP
.B "grid"
draws grid.
.TP
.B "circle"
draws a circle.
.SH "EXIT STATUS"
sxcs exits with status 0 on success, non-zero on abnormal termination.
.SH AUTHORS
NRK <nrk@disroot.org>
.SH BUGS
.SS "Reporting Bugs"
For reporting bugs, either open an issue under the Codeberg repo
<https://codeberg.org/NRK/sxcs> or send an email to <nrk@disroot.org>.
.SS "Known Bugs"
Visual glitches may occur if the cursor size is too big (typically 255x255).
